plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.2'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.lucassellis'
version = '0.0.1-SNAPSHOT'
description = 'Projeto de Notificação - Spring Boot'

java {
    toolchain {
       languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
       extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // --- CORE WEB (O que faltava para rodar na porta 8080) ---
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // --- FUNCIONALIDADES ---
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'

    // --- DOCUMENTAÇÃO (Swagger/OpenAPI) ---
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.6.0'

    // --- UTILITÁRIOS ---
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // --- TESTES ---
    testImplementation 'org.springframework.boot:spring-boot-starter-test' // Starter genérico de teste
    testImplementation 'org.springframework.boot:spring-boot-starter-mail-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-thymeleaf-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}