spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: lucas.sellis@gmail.com
    password: é necessario sempre preencher a senha para p funcionamento do programa
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

envio:
  email:
    remetente: lucas.sellis@gmail.com
    nomeRemetente: Lucas

server:
  port: 8082
